# vich_uploader:
#   db_driver: orm

#   mappings:
#     Film:
#       uri_prefix: /images/Film
#       upload_destination: "%kernel.project_dir%/public/images/Film"
#       namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

# vich_uploader:
#   db_driver: orm
#   storage: flysystem
#   mappings:
#     Film:
#       uri_prefix: /images/Film
#       upload_destination: default.storage
#       namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

vich_uploader:
  db_driver: orm
  storage: flysystem
  mappings:
    Film:
      uri_prefix: https://bucketeer-63e6c1dc-17ea-4ba8-bdd9-82869f667264.s3.eu-west-1.amazonaws.com/images/Film
      upload_destination: default.storage
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
