vich_uploader:
  db_driver: orm

  mappings:
    Film:
      uri_prefix: /images/Film
      upload_destination: "%kernel.project_dir%/public/images/Film"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
